In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import datasets
boston = datasets.load_boston()
features = pd.DataFrame(boston.data,columns=boston.feature_names)
target = pd.DataFrame(boston.target,columns=['target'])

In [16]:
features.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [17]:
target.head()

target
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2

In [18]:
# checking for missing values
features.isna().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
dtype: int64

In [4]:
# as the datapoints differ a lot in magnitude, we'll scale them
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaled_data=scaler.fit_transform(features)

In [5]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(scaled_data,targets,test_size=0.3,random_state=42)

In [6]:
from sklearn.ensemble import RandomForestRegressor

In [7]:
rand_reg = RandomForestRegressor(random_state=6)

In [8]:
rand_reg.fit(train_x,train_y)

D:\ANACONDA\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=6, verbose=0,
                      warm_start=False)

In [9]:
rand_reg.score(test_x,test_y)

0.8612694672179712

In [11]:
import pickle
filename = 'RandomForest_model.pickle'
pickle.dump(rand_reg, open(filename, 'wb'))

In [12]:
features

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

### Ensemble technique - Bagging or BootStrap Aggrigation

multiple decision maker

#### Using RandomForest

In [60]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
bag_reg = BaggingRegressor(base_estimator=RandomForestRegressor(), oob_score=True)

In [61]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(features,target,test_size=0.25,random_state=0)

In [62]:
bag_reg.fit(X_train,y_train)

D:\ANACONDA\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
D:\ANACONDA\lib\site-packages\sklearn\ensemble\_bagging.py:1069: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "


BaggingRegressor(base_estimator=RandomForestRegressor(), oob_score=True)

when we use bag of predictiers the variance reduces than using a single predictiers

In [64]:
# lets check the out of bag score
bag_reg.oob_score_

0.8128128290102185

In [65]:
bag_reg.score(X_test,y_test)

0.7383677405388529

### Using Decison Tree

In [66]:
from sklearn.tree import DecisionTreeRegressor

In [79]:
bag_tree = BaggingRegressor(DecisionTreeRegressor(), oob_score=True)

In [80]:
bag_tree.fit(X_train,y_train)

D:\ANACONDA\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
D:\ANACONDA\lib\site-packages\sklearn\ensemble\_bagging.py:1069: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "


BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True)

In [81]:
bag_tree.score(X_test,y_test)

0.8278219499961532

In [82]:
bag_tree.estimators_features_

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])]

so each estimator takes all the features from the dataset

In [83]:
bag_tree.oob_score_

0.7511458521422908

### Using KNN

In [84]:
from sklearn.neighbors import KNeighborsRegressor

In [89]:
bag_knn = BaggingRegressor(KNeighborsRegressor(),oob_score=True)

In [90]:
bag_knn.fit(X_train,y_train)

D:\ANACONDA\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
D:\ANACONDA\lib\site-packages\sklearn\ensemble\_bagging.py:1069: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "


BaggingRegressor(base_estimator=KNeighborsRegressor(), oob_score=True)

In [91]:
bag_knn.score(X_test,y_test)

0.46980384165290145

In [92]:
bag_knn.oob_score_

0.3707684496745127

so the model has less accuracy but the model is stable (not overlappe) as bagging reduces the variance

the disadvantage of bagging is that we can't see inside the baggingRegressor and see what features and data each estimators are taking so we can't unwrap in bagging 

# RandomForest - default uses Decision tree

In [94]:
from sklearn.ensemble import RandomForestRegressor

In [95]:
rand_reg = RandomForestRegressor()

In [96]:
rand_reg.fit(X_train,y_train)

D:\ANACONDA\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestRegressor()

In [97]:
rand_reg.score(X_test,y_test)

0.7961471117072503

In [130]:
rand_reg.estimators_

[DecisionTreeRegressor(max_features='auto', random_state=1537539954),
 DecisionTreeRegressor(max_features='auto', random_state=143373929),
 DecisionTreeRegressor(max_features='auto', random_state=1708960318),
 DecisionTreeRegressor(max_features='auto', random_state=1513484090),
 DecisionTreeRegressor(max_features='auto', random_state=653930365),
 DecisionTreeRegressor(max_features='auto', random_state=1433789624),
 DecisionTreeRegressor(max_features='auto', random_state=840623671),
 DecisionTreeRegressor(max_features='auto', random_state=347660701),
 DecisionTreeRegressor(max_features='auto', random_state=976381028),
 DecisionTreeRegressor(max_features='auto', random_state=441952780),
 DecisionTreeRegressor(max_features='auto', random_state=160119812),
 DecisionTreeRegressor(max_features='auto', random_state=731544030),
 DecisionTreeRegressor(max_features='auto', random_state=361223317),
 DecisionTreeRegressor(max_features='auto', random_state=144300067),
 DecisionTreeRegressor(max_fea

## Cross-Validation

In [133]:
from sklearn.model_selection import RandomizedSearchCV

from scipy.stats import randint

In [144]:
rf_p_dist={'max_depth':[3,5,10,None],
              'n_estimators':[10,100,200,300,400,500],
              'max_features':randint(1,3),
               'criterion':['gini','mse'],
               'bootstrap':[True,False],
               'min_samples_leaf':randint(1,4),
              }

In [145]:
rdmsearch = RandomizedSearchCV(rand_reg, param_distributions=rf_p_dist,n_jobs=-1, n_iter=40, cv=9)

In [146]:
rdmsearch.fit(X_train,y_train)

D:\ANACONDA\lib\site-packages\sklearn\model_selection\_search.py:921: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan 0.61752854 0.57394278 0.61451106
        nan        nan        nan        nan        nan 0.78701867
 0.72063397 0.8295819  0.62736873        nan 0.82916701 0.71661287
        nan 0.79940051        nan        nan 0.85567612        nan
        nan        nan 0.81011166 0.75043427        nan 0.82588178
        nan 0.74097978        nan 0.77371723        nan 0.71652732
        nan        nan 0.82623072        nan]
  category=UserWarning
D:\ANACONDA\lib\site-packages\sklearn\model_selection\_search.py:880: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


RandomizedSearchCV(cv=9, estimator=RandomForestRegressor(), n_iter=40,
                   n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'criterion': ['gini', 'mse'],
                                        'max_depth': [3, 5, 10, None],
                                        'max_features': <scipy.stats._distn_infrastructure.rv_frozen object at 0x0000011715AA3908>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_frozen object at 0x0000011715AA3988>,
                                        'n_estimators': [10, 100, 200, 300, 400,
                                                         500]})

In [147]:
rdmsearch.best_params_

{'bootstrap': False,
 'criterion': 'mse',
 'max_depth': None,
 'max_features': 1,
 'min_samples_leaf': 1,
 'n_estimators': 500}

In [149]:
rdmsearch.best_score_

0.8556761226101681

In [160]:
RF_reg = RandomForestRegressor(bootstrap=False,criterion='mse',max_depth=None,max_features=1,min_samples_leaf=1,n_estimators=500)

In [166]:
RF_reg.fit(X_train,y_train)

D:\ANACONDA\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestRegressor(bootstrap=False, max_features=1, n_estimators=500)

In [167]:
RF_reg.score(X_test,y_test)

0.6913817337408226